# observability.py
from __future__ import annotations

import json
import os
import time
from dataclasses import dataclass
from typing import Any, Optional

from flask import Flask, jsonify, request
from prometheus_client import Counter, Gauge, Histogram

_OBSERVABILITY = None


@dataclass
class ObservabilityHandles:
    metrics: Any
    tate_requests: Counter
    tate_errors: Counter
    tate_answer_latency: Histogram
    tate_retrieval_requests: Counter
    prediction_requests: Counter
    prediction_errors: Counter
    prediction_latency: Histogram
    prediction_outcomes: Counter
    model_accuracy: Gauge
    model_feature_importance: Gauge
    meilisearch_search_requests: Counter
    meilisearch_search_failures: Counter
    frontend_events: Counter
    exploration_events: Counter
    tate_launcher_events: Counter
    alertmanager_webhooks: Counter
    app_info: Gauge


def get_observability() -> Optional[ObservabilityHandles]:
    return _OBSERVABILITY


def normalize_metric_label(value: Any, default: str = "unknown", max_length: int = 60) -> str:
    """Keep Prometheus labels low-cardinality and safe."""
    text = str(value or default).strip().lower().replace(" ", "_")
    if not text:
        text = default
    allowed = []
    for char in text[:max_length]:
        if char.isalnum() or char in {"_", "-", ":", "/"}:
            allowed.append(char)
        else:
            allowed.append("_")
    return "".join(allowed) or default


def init_pyroscope() -> bool:
    enabled = os.getenv("PYROSCOPE_ENABLED", "true").lower() == "true"
    if not enabled:
        print("Pyroscope profiling disabled by PYROSCOPE_ENABLED=false")
        return False

    try:
        import pyroscope

        pyroscope.configure(
            application_name=os.getenv("PYROSCOPE_APPLICATION_NAME", "titanic-intelligence-backend"),
            server_address=os.getenv("PYROSCOPE_SERVER_ADDRESS", "http://localhost:4040"),
            sample_rate=int(os.getenv("PYROSCOPE_SAMPLE_RATE", "100")),
            detect_subprocesses=False,
            oncpu=True,
            gil_only=True,
            tags={
                "service": "flask-backend",
                "project": "titanic-intelligence-platform",
                "environment": os.getenv("APP_ENV", "development"),
            },
        )
        print("Pyroscope profiling enabled")
        return True
    except Exception as exc:
        print(f"Pyroscope profiling unavailable: {exc}")
        return False


def init_observability(app: Flask) -> ObservabilityHandles:
    global _OBSERVABILITY

    if _OBSERVABILITY is not None:
        return _OBSERVABILITY

    from prometheus_flask_exporter import PrometheusMetrics

    metrics = PrometheusMetrics(app, path="/metrics", export_defaults=True)

    metrics.info(
        "titanic_backend",
        "Titanic Intelligence Platform backend",
        version=os.getenv("APP_VERSION", "1.0.0"),
        environment=os.getenv("APP_ENV", "development"),
    )

    tate_requests = Counter("tate_copilot_requests_total", "Total Tate chat requests", ["context"])
    tate_errors = Counter("tate_copilot_errors_total", "Total Tate chat errors", ["context"])

    tate_answer_latency = Histogram(
        "tate_answer_latency_seconds",
        "Time Tate takes to answer questions",
        ["context"],
        buckets=(0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10, 20),
    )

    tate_retrieval_requests = Counter(
        "tate_retrieval_requests_total",
        "Total Tate retrieval operations",
        ["intent"],
    )

    prediction_requests = Counter("titanic_prediction_requests_total", "Total Titanic ML prediction requests")
    prediction_errors = Counter("titanic_prediction_errors_total", "Total Titanic ML prediction errors")
    prediction_latency = Histogram(
        "titanic_prediction_latency_seconds",
        "Titanic ML prediction endpoint latency",
        buckets=(0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2, 5),
    )
    prediction_outcomes = Counter(
        "titanic_prediction_outcomes_total",
        "Prediction outcomes generated by the Titanic ML endpoint",
        ["prediction_label"],
    )

    model_accuracy = Gauge("titanic_model_accuracy_percent", "Latest model accuracy percentage")
    model_feature_importance = Gauge(
        "titanic_model_feature_importance",
        "Latest model feature importance values",
        ["feature"],
    )

    meilisearch_search_requests = Counter(
        "titanic_meilisearch_search_requests_total",
        "Total passenger searches routed to Meilisearch",
    )
    meilisearch_search_failures = Counter(
        "titanic_meilisearch_search_failures_total",
        "Total Meilisearch failures",
    )

    frontend_events = Counter(
        "titanic_frontend_events_total",
        "Frontend product events",
        ["event_name", "section"],
    )
    exploration_events = Counter(
        "titanic_exploration_events_total",
        "Exploration Journey completed tasks",
        ["task_id"],
    )
    tate_launcher_events = Counter(
        "tate_launcher_events_total",
        "Tate launcher lifecycle events",
        ["event_name"],
    )

    alertmanager_webhooks = Counter(
        "titanic_alertmanager_webhooks_total",
        "Alertmanager webhook payloads received by Flask",
        ["status"],
    )

    pyroscope_enabled = init_pyroscope()

    app_info = Gauge(
        "titanic_observability_info",
        "Static observability setup information",
        ["prometheus", "grafana", "alertmanager", "pyroscope"],
    )
    app_info.labels(
        prometheus="enabled",
        grafana="external",
        alertmanager="enabled",
        pyroscope="enabled" if pyroscope_enabled else "unavailable",
    ).set(1)

    # Prime common label series so Grafana panels show zero instead of "No data" before traffic arrives.
    for context in ["dashboard", "analysis", "regression", "data", "engineering", "unknown"]:
        tate_requests.labels(context=context)
        tate_errors.labels(context=context)
        tate_answer_latency.labels(context=context)

    for intent in ["greeting", "app_help", "prediction", "eda", "passenger_lookup", "rag", "unknown"]:
        tate_retrieval_requests.labels(intent=intent)

    for prediction_label in ["Survived", "Did not survive", "unknown"]:
        prediction_outcomes.labels(prediction_label=prediction_label)

    for event_name in ["tate_opened", "tate_closed", "tate_build_story_clicked", "tate_opened_from_mission"]:
        tate_launcher_events.labels(event_name=event_name)

    @app.route("/api/observability/health", methods=["GET"])
    def observability_health():
        return jsonify({
            "status": "healthy",
            "prometheus_metrics": "/metrics",
            "frontend_event_endpoint": "/api/observability/event",
            "alertmanager_webhook": "/api/observability/alerts",
            "pyroscope_enabled": pyroscope_enabled,
            "pyroscope_server": os.getenv("PYROSCOPE_SERVER_ADDRESS", "http://localhost:4040"),
        })

    @app.route("/api/observability/event", methods=["POST"])
    def frontend_event():
        data = request.get_json(silent=True) or {}
        event_name = normalize_metric_label(data.get("event_name") or data.get("event"), "unknown")
        section = normalize_metric_label(data.get("section") or data.get("activeView"), "unknown")
        task_id = normalize_metric_label(data.get("task_id"), "") if data.get("task_id") else ""

        frontend_events.labels(event_name=event_name, section=section).inc()

        if event_name == "exploration_task_completed" and task_id:
            exploration_events.labels(task_id=task_id).inc()

        if event_name in {"tate_opened", "tate_closed", "tate_build_story_clicked", "tate_opened_from_mission"}:
            tate_launcher_events.labels(event_name=event_name).inc()

        return jsonify({
            "received": True,
            "event_name": event_name,
            "section": section,
            "task_id": task_id or None,
        })

    @app.route("/api/observability/alerts", methods=["POST"])
    def alertmanager_webhook():
        payload = request.get_json(silent=True) or {}
        status = str(payload.get("status", "unknown"))
        alerts = payload.get("alerts", [])
        alertmanager_webhooks.labels(status=status).inc()

        print(
            "ALERTMANAGER_WEBHOOK",
            json.dumps({
                "status": status,
                "alert_count": len(alerts),
                "alerts": [
                    {
                        "status": alert.get("status"),
                        "labels": alert.get("labels", {}),
                        "annotations": alert.get("annotations", {}),
                    }
                    for alert in alerts[:8]
                ],
            }, default=str),
        )

        return jsonify({"received": True, "status": status, "alert_count": len(alerts)})

    _OBSERVABILITY = ObservabilityHandles(
        metrics=metrics,
        tate_requests=tate_requests,
        tate_errors=tate_errors,
        tate_answer_latency=tate_answer_latency,
        tate_retrieval_requests=tate_retrieval_requests,
        prediction_requests=prediction_requests,
        prediction_errors=prediction_errors,
        prediction_latency=prediction_latency,
        prediction_outcomes=prediction_outcomes,
        model_accuracy=model_accuracy,
        model_feature_importance=model_feature_importance,
        meilisearch_search_requests=meilisearch_search_requests,
        meilisearch_search_failures=meilisearch_search_failures,
        frontend_events=frontend_events,
        exploration_events=exploration_events,
        tate_launcher_events=tate_launcher_events,
        alertmanager_webhooks=alertmanager_webhooks,
        app_info=app_info,
    )

    return _OBSERVABILITY


class time_metric:
    def __init__(self, histogram: Histogram, *label_values):
        self.histogram = histogram
        self.label_values = label_values
        self.start: Optional[float] = None

    def __enter__(self):
        self.start = time.perf_counter()
        return self

    def __exit__(self, exc_type, exc, tb):
        if self.start is not None:
            elapsed = time.perf_counter() - self.start
            if self.label_values:
                self.histogram.labels(*self.label_values).observe(elapsed)
            else:
                self.histogram.observe(elapsed)
        return False
